version: "3.8"
services:
  backend:
    # i use image if my base image is on dockerhub
    # image: devopsbackendimage
    # i use build if i am building my own image
    build:
      context: ./api
      dockerfile: Dockerfile
    # another approache can be taken if i have the default docker file name DockerFile
    # build: ./api
    container_name: devopsbackendcontainer
    # using environment variables directly
    # environment:
    #   - MONGO_USERNAME=username
    # load environment variables from env file
    env_file:
      - ./env/dev.env
    # volumes:
    #   - 
    ports:
      - 14600:80
      - 14700:443
  frontend:
    build: ./app
    container_name: devopsfrontendcontainer
    ports:
      - 3000:3000
    # this means that the front end has to wait the backend service to load
    depends_on:
      - backend
    # we use these 2 commans on front end build to run on interactive mode -it
    stdin_open: true
    tty: true
